// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicSchoolApp.Data;

namespace FormsMusicSchool.Migrations
{
    [DbContext(typeof(MusicSchoolDbContext))]
    partial class MusicSchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicSchoolApp.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_achievement")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AchievementDate")
                        .HasColumnName("achievement_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AchievementTypeId")
                        .HasColumnName("id_achievement_type")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnName("id_course")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("UserId")
                        .HasColumnName("id_user")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementTypeId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("achievement");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.AchievementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_achievement_type")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnName("achievement_type")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("achievement_type");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_benefit")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BenefitName")
                        .IsRequired()
                        .HasColumnName("benefit")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("PercentOfBenefit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("benefit");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_schedule")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Classroom")
                        .IsRequired()
                        .HasColumnName("classroom")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("DayOfWeek")
                        .IsRequired()
                        .HasColumnName("day_of_week")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnName("end_time")
                        .HasColumnType("time");

                    b.Property<int?>("GroupId")
                        .HasColumnName("id_group")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnName("start_time")
                        .HasColumnType("time");

                    b.Property<int?>("TeacherId")
                        .HasColumnName("id_user")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeacherId");

                    b.ToTable("class_schedule");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_contract")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AmountMonth")
                        .IsRequired()
                        .HasColumnName("amount_month")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("ContractDate")
                        .HasColumnName("contract_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnName("id_course")
                        .HasColumnType("int");

                    b.Property<bool?>("Discount")
                        .HasColumnName("discount")
                        .HasColumnType("bit");

                    b.Property<int?>("DiscountSum")
                        .HasColumnName("discount_sum")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnName("id_user")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("contract");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_course")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseTypeId")
                        .HasColumnName("id_course_type")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnName("duration_course")
                        .HasColumnType("int");

                    b.Property<int?>("MaxAge")
                        .HasColumnName("max_age")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnName("min_age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name_course")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Price")
                        .HasColumnName("price")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnName("id_user")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseTypeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("course");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.CourseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_course_type")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnName("course_type")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("corse_type");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_group_member")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupId")
                        .HasColumnName("id_group")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnName("join_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnName("id_student")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("group_members");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_parent")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Number")
                        .HasColumnName("number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnName("surname")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("parent");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_progress")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseId")
                        .HasColumnName("id_course")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EvaluationDate")
                        .HasColumnName("evaluation_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("SkillLevel")
                        .HasColumnName("skill_level")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("StudentId")
                        .HasColumnName("id_student")
                        .HasColumnType("int");

                    b.Property<string>("TeacherComment")
                        .HasColumnName("teacher_comment")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("TeacherId")
                        .HasColumnName("id_user")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("progress");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_role")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnName("role")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("role");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.StudyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_group")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseId")
                        .HasColumnName("id_course")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentStudents")
                        .HasColumnName("current_students")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnName("group_name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsActive")
                        .HasColumnName("is_active")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxStudents")
                        .HasColumnName("max_students")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnName("id_teacher")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("study_group");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_user")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BenefitId")
                        .HasColumnName("id_benefit")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("login")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Number")
                        .HasColumnName("number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnName("id_parent")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Patronymic")
                        .HasColumnName("patronymic")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("RoleId")
                        .HasColumnName("id_role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnName("surname")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Achievement", b =>
                {
                    b.HasOne("MusicSchoolApp.Models.AchievementType", "AchievementType")
                        .WithMany("Achievements")
                        .HasForeignKey("AchievementTypeId");

                    b.HasOne("MusicSchoolApp.Models.Course", "Course")
                        .WithMany("Achievements")
                        .HasForeignKey("CourseId");

                    b.HasOne("MusicSchoolApp.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.ClassSchedule", b =>
                {
                    b.HasOne("MusicSchoolApp.Models.StudyGroup", "Group")
                        .WithMany("Schedules")
                        .HasForeignKey("GroupId");

                    b.HasOne("MusicSchoolApp.Models.User", "Teacher")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Contract", b =>
                {
                    b.HasOne("MusicSchoolApp.Models.Course", "Course")
                        .WithMany("Contracts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSchoolApp.Models.User", "User")
                        .WithMany("Contracts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Course", b =>
                {
                    b.HasOne("MusicSchoolApp.Models.CourseType", "CourseType")
                        .WithMany("Courses")
                        .HasForeignKey("CourseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSchoolApp.Models.User", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicSchoolApp.Models.GroupMember", b =>
                {
                    b.HasOne("MusicSchoolApp.Models.StudyGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSchoolApp.Models.User", "Student")
                        .WithMany("GroupMembers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicSchoolApp.Models.Progress", b =>
                {
                    b.HasOne("MusicSchoolApp.Models.Course", "Course")
                        .WithMany("Progresses")
                        .HasForeignKey("CourseId");

                    b.HasOne("MusicSchoolApp.Models.User", "Student")
                        .WithMany("Progresses")
                        .HasForeignKey("StudentId");

                    b.HasOne("MusicSchoolApp.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.StudyGroup", b =>
                {
                    b.HasOne("MusicSchoolApp.Models.Course", "Course")
                        .WithMany("StudyGroups")
                        .HasForeignKey("CourseId");

                    b.HasOne("MusicSchoolApp.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("MusicSchoolApp.Models.User", b =>
                {
                    b.HasOne("MusicSchoolApp.Models.Benefit", "Benefit")
                        .WithMany("Users")
                        .HasForeignKey("BenefitId");

                    b.HasOne("MusicSchoolApp.Models.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("MusicSchoolApp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
